gitbucket:
  image: takezoe/gitbucket:4
  ports:
    - "8080:8080"
    - "29418:29418"
  volumes:
    - ./data:/gitbucket
    - /etc/localtime:/etc/localtime:ro
  environment:
    - TZ=Asia/Tokyo
  command: java -jar /opt/gitbucket.war --prefix=/gitbucket