data-mysql:
  image: busybox:buildroot-2014.02
  volumes:
    - ./workspace:/var/lib/mysql
    - ./mysql:/docker-entrypoint-init.d
mysql:
  image: mysql:5.6.28
  environment:
    MYSQL_ROOT_PASSWORD: root
  volumes_from:
    - data-mysql
  ports:
    - "3306:3306"
etherpad:
  image: tvelocity/etherpad-lite
  ports:
    - "9001:9001"
  links:
    - mysql:mysql
  environment:
    - ETHERPAD_ADMIN_PASSWORD=takumon
