FROM busybox:latest

MAINTAINER Takumon <inouetakumon@gmail.com>

#sonarqube
VOLUME /opt/sonarqube/conf
VOLUME /opt/sonarqube/data
VOLUME /opt/sonarqube/extentions
VOLUME /opt/sonarqube/lib/bundled-plugins
#postgresql
VOLUME /var/lib/postgresql
VOLUME /var/lib/postgresql/data

CMD /bin/sh
