version: '2'

services:
  rocketchat:
    image: rocketchat/rocket.chat:0.60.2
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3001
　     - ROOT_URL=http://[Rocketchat IP-Address]:3001
      # - ROOT_URL=http://10.74.65.209:3001
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - Accounts_UseDNSDomainCheck=false
      - TZ=Asia/Tokyo
      # - HTTP_PROXY=http://id:password@proxy.domain.com
      # - HTTPS_PROXY=http://id:password@proxy.domain.com
    depends_on:
      - mongo
    ports:
      - 3001:3001

  mongo:
    image: mongo:3.6.1
    restart: unless-stopped
    volumes:
     - ./db:/data/db
     - ./dump:/dump
     - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Tokyo
    command: mongod --smallfiles --oplogSize 128

  hubot:
    image: rocketchat/hubot-rocketchat:v1.0.11
    ports:
      - 3002:8080
    volumes:
      - ./hubot/scripts:/home/hubot/scripts
      - ./hubot/hubot-scripts.json:/home/hubot/hubot-scripts.json
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Tokyo
      - ROCKETCHAT_URL=rocketchat:3001
      - ROCKETCHAT_ROOM=GENERAL
      - ROCKETCHAT_ROOM=hubot
      - ROCKETCHAT_USER=rocketchatbot
      # パスワードを設定
      - ROCKETCHAT_PASSWORD=[rocketchat password]
      # - ROCKETCHAT_PASSWORD=XXXXXXX
      - BOT_NAME=RocketchatBot
      - EXTERNAL_SCRIPTS=hubot-diagnostics,hubot-help,hubot-seen,hubot-links,hubot-greetings,cheerio,request
      - HUBOT_JENKINS_URL=http://[jenkins IP-Address]:[Jenkins port]
      # - HUBOT_JENKINS_URL=http://10.74.65.209:10080
      - HUBOT_JENKINS_AUTH=[jenkins user]:[jenkins password]
      # - HUBOT_JENKINS_AUTH=admin:admin
      # - HTTP_PROXY=http://id:password@proxy.domain.com
      # - HTTPS_PROXY=http://id:password@proxy.domain.com
    depends_on:
      - rocketchat

