version: '2'

services:
  rocketchat:
    image: rocketchat/rocket.chat:0.60.3
    restart: unless-stopped
    volumes:
      - ./rocketchat/uploads:/app/uploads
    environment:
      - PORT=3001
      # - ROOT_URL=http://[Rocketchat IP-Address]:3001
      - ROOT_URL=http://192.168.1.5:3001
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - Accounts_UseDNSDomainCheck=false
      - TZ=Asia/Tokyo
    depends_on:
      - mongo
    ports:
      - 3001:3001

  mongo:
    image: mongo:3.6.1
    restart: unless-stopped
    volumes:
     - ./mongodb/data:/data/db
     - ./mongodb/dump:/dump
     - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Tokyo
    command: mongod --smallfiles --oplogSize 128

  hubot:
    image: takumon/hubot-rocketchat-with-puppeteer
    # image: rocketchat/hubot-rocketchat:v1.0.11
    shm_size: 512m
    ports:
      - 3002:8080
    volumes:
      - ./hubot/scripts:/home/hubot/scripts
      - ./hubot/hubot-scripts.json:/home/hubot/hubot-scripts.json
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Tokyo
      - ROCKETCHAT_URL=rocketchat:3001
      - ROCKETCHAT_ROOM=hubot
      - ROCKETCHAT_USER=bot
      - ROCKETCHAT_PASSWORD=bot
      - BOT_NAME=bot
      - EXTERNAL_SCRIPTS=hubot-diagnostics,hubot-help,hubot-seen,hubot-links,hubot-greetings,cheerio,request,hubot-redis-brain
      # - HUBOT_JENKINS_URL=http://[jenkins IP-Address]:[Jenkins port]
      - HUBOT_JENKINS_URL=http://192.168.1.5:10080/jenkins/
      # - HUBOT_JENKINS_AUTH=[jenkins user]:[jenkins password]
      - HUBOT_JENKINS_AUTH=admin:admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - rocketchat
      - redis

  redis:
    image: redis:4.0.6
    restart: unless-stopped
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
    volumes:
      - ./redis/data:/data
